name: marvel_universe
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #CORE 
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  # NETWORK
  dio: ^4.0.6
  # STATE MANAGEMENT
  flutter_bloc: ^8.0.1
  # PRESENTATION
  font_awesome_flutter: ^10.1.0
  page_transition: ^2.0.5
  shimmer: ^2.0.0
  # LOCALIZATION
  easy_localization: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.1.6

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ec1d25"
  image: "assets/images/logo.png"


flutter_icons:
  image_path: "assets/images/logoWithBg.png"
  android: true
  ios: true


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
